admin_panel/urls.py
from django.urls import path
from admin_panel.views.prodcut_views import ProductListView, ProductCreateView, ProductUpdateView, ProductDeleteView
from admin_panel.views.product_category_views import ProductCategoryListView, ProductCategoryCreateView, \
    ProductCategoryUpdateView, ProductCategoryDeleteView

app_name = 'admin_panel'

urlpatterns = [
    path('product-categories/', ProductCategoryListView.as_view(), name='product_category_list'),
    path('product-categories/create', ProductCategoryCreateView.as_view(), name='product_category_create'),
    path('product-categories/<int:pk>/update/', ProductCategoryUpdateView.as_view(), name='product_category_update'),
    path('product-categories/<int:pk>/delete/', ProductCategoryDeleteView.as_view(), name='product_category_delete'),

    path('products/', ProductListView.as_view(), name='product_list'),
    path('products/create', ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
]

online_store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy('admin_panel:product_category_list')), name='home'),
    path('admin/', admin.site.urls),
    path('admin-panel/', include('admin_panel.urls')),
    path('api/', include('rest_api.urls')),
    path("accounts/login/", LoginView.as_view(), name="login"),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

rest_api/urls.py
from django.urls import path

from rest_api.views import ProductCategoryListView, ProductListView, ProductDetailsView, ProductCategoryDetailsView, \
    ProductCategoryCreateView, ProductCategoryUpdateView

app_name = 'rest_api'

urlpatterns = [
    path('product-categories', ProductCategoryListView.as_view(), name='product_category_list'),
    path('product-categories/create', ProductCategoryCreateView.as_view(), name='product_category_create'),
    path('product-categories/<int:pk>', ProductCategoryDetailsView.as_view(), name='product_category_details'),
    path('product-categories/<int:pk>/update', ProductCategoryUpdateView.as_view(), name='product_category_update'),
    path('products', ProductListView.as_view(), name='product_list'),
    path('products/<int:pk>', ProductDetailsView.as_view(), name='product_details'),
]

admin_panel/models.py
from django.db import models

# Create your models here.

admin_panel/forms.py
from django import forms

from products.models import Product, ProductCategory


class ProductCategoryForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = ['title_en', 'title_ar', 'description_en', 'description_ar']

    def __init__(self, *args, **kwargs):
        self.updated_by = kwargs.pop('updated_by')
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        if not self.instance.pk:
            self.instance.created_by = self.updated_by
        self.instance.updated_by = self.updated_by
        return super().save(commit)


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['category', 'title_en', 'title_ar', 'model_number', 'description_en', 'description_ar', 'quantity',
                  'price']

    def __init__(self, *args, **kwargs):
        self.updated_by = kwargs.pop('updated_by')
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        if not self.instance.pk:
            self.instance.created_by = self.updated_by
        self.instance.updated_by = self.updated_by
        return super().save(commit)

admin_panel/views.py
from django.contrib import messages
from django.db.models import Count
from django.http import HttpResponseBadRequest
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, UpdateView, CreateView, DeleteView
from django.utils.translation import gettext as _

from products.models import ProductCategory


# Create your views here.

class ProductCategoryListView(ListView):
    model = ProductCategory
    template_name = 'admin_panel/product_categories/product_categories_list.html'
    context_object_name = 'product_categories'

    def get_queryset(self):
        return super().get_queryset().annotate(products_count=Count('products'))


class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    fields = ['title_en', 'title_ar', 'description_en', 'description_ar']
    template_name = 'admin_panel/product_categories/product_category_update.html'
    success_url = reverse_lazy('admin_panel:product_category_list')
    context_object_name = 'product_category'


class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    fields = ['title_en', 'title_ar', 'description_en', 'description_ar']
    template_name = 'admin_panel/product_categories/product_category_create.html'
    success_url = reverse_lazy('admin_panel:product_category_list')


class ProductCategoryDeleteView(DeleteView):
    model = ProductCategory
    success_url = reverse_lazy('admin_panel:product_category_list')

    def get_queryset(self):
        return super().get_queryset().annotate(product_count=Count('products'))

    def delete(self, request, *args, **kwargs):
        product_category = self.get_object()
        if product_category.product_count != 0:
            return HttpResponseBadRequest()
        response = super().delete(request, *args, **kwargs)
        messages.success(request, _('Product category is deleted successfully'))
        return response

admin_panel/views/base.py
from django.views import View
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import DeletionMixin


class DeleteView(DeletionMixin, SingleObjectMixin, View):
    pass

admin_panel/views/prodcut_views.py
from django.contrib import messages
from django.db.models import Sum, Count
from django.http import HttpResponseBadRequest
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, CreateView
from django.utils.translation import gettext as _

from admin_panel.mixins import SystemAdminAccessMixin, ProductBaseFormMixin
from admin_panel.views.base import DeleteView
from products.models import Product, ProductImage


class ProductListView(SystemAdminAccessMixin, ListView):
    model = Product
    template_name = 'admin_panel/products/product_list.html'
    context_object_name = 'products'
    paginate_by = 10

    def get_queryset(self):
        return super().get_queryset().annotate(order_sum=Sum('orders__quantity', distinct=True, default=0),
                                               cart_items_count=Count("cart_items", distinct=True))


class ProductCreateView(SystemAdminAccessMixin, ProductBaseFormMixin, CreateView):
    template_name = 'admin_panel/products/product_create.html'
    success_message = _('Product was created successfully')

    def post(self, request, *args, **kwargs):
        self.object = None
        return super().post(request, *args, **kwargs)

    def save_product_images(self, product_image_formset):
        product_images = product_image_formset.save(commit=False)
        for product_image in product_images:
            product_image.product = self.object
        ProductImage.objects.bulk_create(product_images, update_fields='file', unique_fields='id')


class ProductUpdateView(SystemAdminAccessMixin, ProductBaseFormMixin, UpdateView):
    template_name = 'admin_panel/products/product_update.html'
    context_object_name = 'product'
    success_message = _('Product was updated successfully')

    def get_queryset(self):
        return super().get_queryset().prefetch_related('product_images')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)


class ProductDeleteView(SystemAdminAccessMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('admin_panel:product_list')
    success_message = _('Product was deleted successfully')

    def get_queryset(self):
        return super().get_queryset().annotate(order_sum=Sum('orders__quantity', distinct=True, default=0),
                                               cart_items_count=Count("cart_items", distinct=True))

    def delete(self, request, *args, **kwargs):
        product = self.get_object()
        if product.order_sum != 0 or product.cart_items_count != 0:
            return HttpResponseBadRequest()
        response = super().delete(request, *args, **kwargs)
        messages.success(request, self.success_message)
        return response

admin_panel/views/product_category_views.py
from django.contrib import messages
from django.db.models import Count
from django.http import HttpResponseBadRequest
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, CreateView
from django.utils.translation import gettext as _

from admin_panel.mixins import SystemAdminAccessMixin
from admin_panel.views.base import DeleteView
from products.forms import ProductCategoryForm
from products.models import ProductCategory


# Create your views here.

class ProductCategoryListView(SystemAdminAccessMixin, ListView):
    model = ProductCategory
    template_name = 'admin_panel/product_categories/product_categories_list.html'
    context_object_name = 'product_categories'
    paginate_by = 10

    def get_queryset(self):
        return super().get_queryset().annotate(products_count=Count('products'))


class ProductCategoryCreateView(SystemAdminAccessMixin, CreateView):
    model = ProductCategory
    form_class = ProductCategoryForm
    template_name = 'admin_panel/product_categories/product_category_create.html'
    success_url = reverse_lazy('admin_panel:product_category_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['updated_by'] = self.request.user
        return kwargs


class ProductCategoryUpdateView(SystemAdminAccessMixin, UpdateView):
    model = ProductCategory
    form_class = ProductCategoryForm
    template_name = 'admin_panel/product_categories/product_category_update.html'
    success_url = reverse_lazy('admin_panel:product_category_list')
    context_object_name = 'product_category'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['updated_by'] = self.request.user
        return kwargs


class ProductCategoryDeleteView(SystemAdminAccessMixin, DeleteView):
    model = ProductCategory
    success_url = reverse_lazy('admin_panel:product_category_list')

    def get_queryset(self):
        return super().get_queryset().annotate(product_count=Count('products'))

    def delete(self, request, *args, **kwargs):
        product_category = self.get_object()
        if product_category.product_count != 0:
            return HttpResponseBadRequest()
        response = super().delete(request, *args, **kwargs)
        messages.success(request, _('Product category is deleted successfully'))
        return response

admin_panel/templates/admin_panel/product_categories/product_categories_list.html
{% extends 'admin_panel/base/base.html' %}
{% load static i18n %}
{% block content %}
    <main class="main-content position-relative border-radius-lg ">
        <div class="container-fluid py-4">
            <div class="row">
                <div class="col-12 text-right">
                    <a class="btn btn-primary d-flex float-end" role="button"
                       href="{% url 'admin_panel:product_category_create' %}">
                        <i class="icon ion-plus-round me-2"></i>
                        {% translate "Create New Prodcut Category" %}
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="card mb-4">
                        <div class="card-header pb-0">
                            <h6>{% translate 'Product Categories' %}</h6>
                        </div>
                        <div class="card-body px-0 pt-0 pb-2">
                            <div class="table-responsive p-0">
                                <table class="table align-items-center mb-0">
                                    <thead>
                                    <tr>
                                        <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                            {% translate 'Title En' %}
                                        </th>
                                        <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                                            {% translate 'Title Ar' %}
                                        </th>
                                        <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                            {% translate 'Created By' %}
                                        </th>
                                        <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                            {% translate 'Created At' %}
                                        </th>
                                        <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                            {% translate '#Products' %}
                                        </th>
                                        <th class="text-secondary opacity-7"></th>
                                        <th class="text-secondary opacity-7"></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for product_category in product_categories %}
                                        <tr>
                                            <td>
                                                <div class="d-flex px-2 py-1">
                                                    <div class="d-flex flex-column justify-content-center">
                                                        <h6 class="mb-0 text-sm">{{ product_category.title_en }}</h6>
                                                    </div>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="d-flex px-2 py-1">
                                                    <div class="d-flex flex-column justify-content-center">
                                                        <h6 class="mb-0 text-sm">{{ product_category.title_ar }}</h6>
                                                    </div>
                                                </div>
                                            </td>
                                            <td class="text-center">
                                                <h6 class="mb-0 text-sm ">{{ product_category.created_by.last_name }}</h6>
                                            </td>
                                            <td class="text-center">
                                                <h6 class="mb-0 text-sm">{{ product_category.created_at }}</h6>
                                            </td>
                                            <td class="text-center">
                                                <h6 class="mb-0 text-sm">{{ product_category.products_count }}</h6>
                                            </td>
                                            <td class="align-middle">
                                                <a href="{% url 'admin_panel:product_category_update' product_category.pk %}"
                                                   class="text-secondary font-weight-bold text-xs">
                                                    {% translate 'Update' %}
                                                </a>
                                            </td>
                                            <td class="align-middle">
                                                {% if product_category.products_count == 0 %}
                                                    <form method="post"
                                                          action="{% url 'admin_panel:product_category_delete' product_category.pk %}">
                                                        {% csrf_token %}
                                                        <button type="submit" name="delete"
                                                                class="btn text-danger delete-product-category">
                                                            <i class="fa fa-trash"></i>
                                                            {% translate 'Delete' %}
                                                        </button>
                                                    </form>
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            <div class="p-2">
                                {% include 'pagination.html' %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

{% block extra_js %}
    <script type="application/javascript">
        $(document).ready(function () {
            $(".delete-product-category").click(function (event) {
                if (confirm("{% translate 'Are you sure you want to delete this product category?' %}") == true) {
                    $(event.target).closest('form').submit();
                } else {
                    event.preventDefault();
                }
            });
        });
    </script>
{% endblock extra_js %}

admin_panel/templates/admin_panel/product_categories/product_category_base_form.html
{% extends 'admin_panel/base/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <main class="main-content position-relative border-radius-lg ">

        <div class="container-fluid py-4">
            <div class="row">
                <div class="col-12">
                    <div class="card mb-4">
                        <div class="card-header pb-0">
                            {% block card_title %}
                            {% endblock %}
                        </div>
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="form-group col-md-6 mb-0">
                                        {{ form.title_en|as_crispy_field }}
                                    </div>
                                    <div class="form-group col-md-6 mb-0">
                                        {{ form.title_ar|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-md-12 mb-0">
                                        {{ form.description_en|as_crispy_field }}
                                    </div>
                                </div>
                                 <div class="form-row">
                                    <div class="form-group col-md-12 mb-0">
                                        {{ form.description_ar|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="text-right">
                                    {% block buttons %}
                                    {% endblock %}
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

admin_panel/templates/admin_panel/product_categories/product_category_create.html
{% extends 'admin_panel/product_categories/product_category_base_form.html' %}
{% load i18n %}
{% block card_title %}
    <h6>{% translate 'Create New Product Category' %}</h6>
{% endblock %}
{% block buttons %}
    <button type="submit" class="btn btn-primary">{% translate 'Create' %}</button>
{% endblock %}

admin_panel/templates/admin_panel/product_categories/product_category_update.html
{% extends 'admin_panel/product_categories/product_category_base_form.html' %}
{% load i18n %}
{% block card_title %}
    <h6>{% translate 'Update' %} {{ product_category.title_en }} {% translate 'Prodcut Category' %}</h6>
{% endblock %}
{% block buttons %}
    <button type="submit" class="btn btn-primary">{% translate 'Update' %}</button>
{% endblock %}